export DOTFILES=$HOME/dotfiles
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$DOTFILES/zsh/zsh_custom
export EDITOR='vim'
export VISUAL='vim'
export PATH="$PATH:/usr/local/Cellar/postgresql@11/$( ls -tr /usr/local/Cellar/postgresql@11 | tail -n 1)/bin"

PATH=""
PATH="$PATH:/usr/local/opt/python/libexec/bin"
PATH="$PATH:/usr/local/lib/ruby/gems/2.6.0/bin"
PATH="$PATH:/usr/local/opt/ruby/bin"
PATH="$PATH:/usr/local/bin"
PATH="$PATH:/usr/bin"
PATH="$PATH:/bin"
PATH="$PATH:/usr/sbin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="/usr/local/sbin:$PATH"
export HOMEBREW_NO_INSECURE_REDIRECT=1
# export HOMEBREW_CASK_OPTS=--require-sha
export HOMEBREW_NO_ANALYTICS=1

# ZSH_THEME="bullet-train"

BULLETTRAIN_PROMPT_ORDER=(status dir git cmd_exec_time)
BULLETTRAIN_PROMPT_SEPARATE_LINE=false
BULLETTRAIN_GIT_COLORIZE_DIRTY=true
BULLETTRAIN_PROMPT_CHAR=''
BULLETTRAIN_EXEC_TIME_BG=white
BULLETTRAIN_EXEC_TIME_FG=black

#################

plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

source ~/.aliases

# Machine-specific config
[ -f ~/.private-env ] && source ~/.private-env
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# nvm setup
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

eval "$(rbenv init -)"
eval "$(pyenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/okhan/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/okhan/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/okhan/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/okhan/google-cloud-sdk/completion.zsh.inc'; fi
